# Generated by Django 2.0.7 on 2018-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_categorie_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='lien',
            field=models.URLField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='articles',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
